// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAvniABVGM5zEh2w7eRQMhvuJcWAol8fQ',
    appId: '1:1017195976044:ios:7eee91d18c48e097814f49',
    messagingSenderId: '1017195976044',
    projectId: 'first-project-69cd1',
    storageBucket: 'first-project-69cd1.firebasestorage.app',
    iosClientId: '1017195976044-0ke3oefooc7ms0dhv2tb3vtfggc5978m.apps.googleusercontent.com',
    iosBundleId: 'com.example.alGamalAlMassi',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBbYHPrN73iSD7pXA8EuSC9C-GFM7okfo',
    appId: '1:1017195976044:android:88e38df5ec3867f4814f49',
    messagingSenderId: '1017195976044',
    projectId: 'first-project-69cd1',
    storageBucket: 'first-project-69cd1.firebasestorage.app',
  );

}